<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var backend\models\Actividades $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="actividades-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Actividades',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'desc')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'ciclo_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Ciclos::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'turno_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Turnos::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'curso_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Cursos::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'materia_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Materias::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'profesor_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Profesores::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'tipo_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\TipoActividades::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'bimestre_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Bimestres::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= $form->field($model, 'fecha')->textInput() ?>
			<?= $form->field($model, 'puntaje_max')->textInput() ?>
			<?= $form->field($model, 'created_at')->textInput() ?>
			<?= $form->field($model, 'created_by')->textInput() ?>
			<?= $form->field($model, 'updated_at')->textInput() ?>
			<?= $form->field($model, 'updated_by')->textInput() ?>
			<?= $form->field($model, 'deleted')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => Yii::t('backend', StringHelper::basename('backend\models\Actividades')),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

