<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use \kartik\depdrop\Depdrop;
use kartik\date\DatePicker;
use \kartik\file\FileInput;
use \kartik\select2\Select2;

/**
* @var yii\web\View $this
* @var backend\models\Choferes $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="choferes-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Choferes',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options' => ['enctype' => 'multipart/form-data'],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'nombres')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_pat')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_mat')->textInput(['maxlength' => true]) ?>
			<?= 
                $form->field($model, 'fec_nac')->widget(DatePicker::classname(), [
                    'options' => ['placeholder' => Yii::t('backend', 'Ingrese una Fecha')],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'autoclose'=>true
                    ]
                ]); 
            ?>
            <?= 
                $form->field($model, 'sex')->dropDownList(
                    ['F'=>'Femenino', 'M'=>'Masculino'],
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
            
            <div class="row">
              <div class="col-xs-10 col-md-6 col-md-push-3">
                <a href="#" class="thumbnail">
                  <img src="<?= $model->ruta_foto; ?>" alt="<?= $model->ruta_foto; ?>" class="img-thumbnail">
                </a>
              </div>
            </div>

            <?= 
                $form->field($model, 'archivo')->widget(FileInput::classname(), [
                    'name' => 'archivo',
                    'pluginOptions' => [
                        'showUpload' => false,
                        'allowedFileTypes' => ['image'],
                        'allowedFileExtensions' => ['jpg', 'jpeg', 'png'],
                    ]
                ]); 
            ?>

            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'pais_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\Paises::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select'),
                     'id'=>'pais-id']
                ); 
            ?>
            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'estado_id')->widget(DepDrop::classname(), [
                    'options'=>['id'=>'estado-id'],
                    'data'=>\yii\helpers\ArrayHelper::map(backend\models\Estados::find($model->estado_id)->all(), 'id', 'nombre'),
                    'pluginOptions'=>[
                        'depends'=>['pais-id'],
                        'initialize' => true,
                        'initDepends'=>['pais-id'],
                        'placeholder'=>Yii::t('backend', 'Select'),
                        'url'=>Url::to(['/paises/estados'])
                    ]
                ]); 
            ?>
			<?= $form->field($model, 'tipo_sangre')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_emergencia')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'contacto_emergencia')->textInput(['maxlength' => true]) ?>
			<?php
                echo $form->field($model, 'user_id')->widget(Select2::classname(), [
                    'name' => 'user_id',
                    'data' => ArrayHelper::map($usersQuery, 'id', 'username'),
                    'options' => ['placeholder' => Yii::t('backend', 'Select')],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ]);
            ?>

            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'tipo_doc_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\TipoDocumentos::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
			<?= $form->field($model, 'num_doc_id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'direc')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'categoria_licencia')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'num_licencia')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => Yii::t('backend', StringHelper::basename('backend\models\Choferes')),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

