<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use \kartik\depdrop\Depdrop;
use kartik\date\DatePicker;

/**
* @var yii\web\View $this
* @var backend\models\Padres $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="padres-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Padres',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'nombres')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_pat')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_mat')->textInput(['maxlength' => true]) ?>
			<?= 
                $form->field($model, 'fec_nac')->widget(DatePicker::classname(), [
                    'options' => ['placeholder' => Yii::t('backend', 'Ingrese una Fecha')],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'autoclose'=>true
                    ]
                ]); 
            ?>
            <?= 
                $form->field($model, 'sex')->dropDownList(
                    ['F'=>'Femenino', 'M'=>'Masculino'],
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
			<?= $form->field($model, 'ruta_foto')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'pais_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\Paises::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select'),
                     'id'=>'pais-id']
                ); 
            ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'estado_id')->widget(DepDrop::classname(), [
                    'options'=>['id'=>'estado-id'],
                    'pluginOptions'=>[
                        'depends'=>['pais-id'],
                        'placeholder'=>Yii::t('backend', 'Select'),
                        'url'=>Url::to(['/paises/estados'])
                    ]
                ]); 
            ?>
			<?= $form->field($model, 'tipo_sangre')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_emergencia')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'contacto_emergencia')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'user_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\User::find()->all(), 'id', 'username'),
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'tipo_doc_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\TipoDocumentos::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
			<?= $form->field($model, 'num_doc_id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'direc')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'profesion')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nit')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'razon_social')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'active')->checkbox() ?>

        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => Yii::t('backend', StringHelper::basename('backend\models\Padres')),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

