<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use \kartik\depdrop\Depdrop;
use kartik\date\DatePicker;
use \kartik\file\FileInput;
use \kartik\select2\Select2;
use wbraganca\dynamicform\DynamicFormWidget;

use backend\models\Estudiantes;

/**
* @var yii\web\View $this
* @var backend\models\Padres $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="padres-form">

    <?php $form = ActiveForm::begin([
    'id' => 'dynamic-form',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options' => ['enctype' => 'multipart/form-data'],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'nombres')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_pat')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_mat')->textInput(['maxlength' => true]) ?>
			<?= 
                $form->field($model, 'fec_nac')->widget(DatePicker::classname(), [
                    'options' => ['placeholder' => Yii::t('backend', 'Ingrese una Fecha')],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'autoclose'=>true
                    ]
                ]); 
            ?>
            <?= 
                $form->field($model, 'sex')->dropDownList(
                    ['F'=>'Femenino', 'M'=>'Masculino'],
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>

            <div class="row">
              <div class="col-xs-10 col-md-6 col-md-push-3">
                <a href="#" class="thumbnail">
                  <img src="<?= $model->ruta_foto; ?>" alt="<?= $model->ruta_foto; ?>" class="img-thumbnail">
                </a>
              </div>
            </div>

			<?= 
                $form->field($model, 'archivo')->widget(FileInput::classname(), [
                    'name' => 'archivo',
                    'pluginOptions' => [
                        'showUpload' => false,
                        'allowedFileTypes' => ['image'],
                        'allowedFileExtensions' => ['jpg', 'jpeg', 'png'],
                    ]
                ]); 
            ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'pais_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\Paises::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select'),
                     'id'=>'pais-id']
                ); 
            ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'estado_id')->widget(DepDrop::classname(), [
                    'options'=>['id'=>'estado-id'],
                    'data'=>\yii\helpers\ArrayHelper::map(backend\models\Estados::find($model->estado_id)->all(), 'id', 'nombre'),
                    'pluginOptions'=>[
                        'depends'=>['pais-id'],
                        'initialize' => true,
                        'initDepends'=>['pais-id'],
                        'placeholder'=>Yii::t('backend', 'Select'),
                        'url'=>Url::to(['/paises/estados'])
                    ]
                ]); 
            ?>
			<?= $form->field($model, 'tipo_sangre')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_emergencia')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'contacto_emergencia')->textInput(['maxlength' => true]) ?>

            <?php
                echo $form->field($model, 'user_id')->widget(Select2::classname(), [
                    'name' => 'user_id',
                    'data' => ArrayHelper::map($usersQuery, 'id', 'username'),
                    'options' => ['placeholder' => Yii::t('backend', 'Select')],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ]);
            ?>

			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model, 'tipo_doc_id')->dropDownList(
                    \yii\helpers\ArrayHelper::map(backend\models\TipoDocumentos::find()->all(), 'id', 'nombre'),
                    ['prompt' => Yii::t('backend', 'Select')]
                ); 
            ?>
			<?= $form->field($model, 'num_doc_id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'direc')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil_trabajo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'profesion')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nit')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'razon_social')->textInput(['maxlength' => true]) ?>
            
            <?php
                echo $form->field($model, 'conyuge_id')->widget(Select2::classname(), [
                    'name' => 'conyuge_id',
                    'data' => ArrayHelper::map($padresQuery, 'id', 'fullnameinverted'),
                    'options' => ['placeholder' => Yii::t('backend', 'Select')],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ]);
            ?>

			<?= $form->field($model, 'active')->checkbox() ?>

        </p>
        <?php $this->endBlock(); ?>

        <?php $this->beginBlock('hijos'); ?>
        <p>
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading"><h4><i class="glyphicon glyphicon-envelope"></i> Lista de Hijos</h4></div>
                    <div class="panel-body">
                         <?php DynamicFormWidget::begin([
                            'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                            'widgetBody' => '.container-items', // required: css class selector
                            'widgetItem' => '.item', // required: css class
                            'limit' => 10, // the maximum times, an element can be cloned (default 999)
                            'min' => 1, // 0 or 1 (default 1)
                            'insertButton' => '.add-item', // css class
                            'deleteButton' => '.remove-item', // css class
                            'model' => $modelsHijos[0],
                            'formId' => 'dynamic-form',
                            'formFields' => [
                                'estudiante_id',
                            ],
                        ]); ?>

                        <div class="container-items"><!-- widgetContainer -->
                        <?php foreach ($modelsHijos as $i => $modelHijos): ?>
                            <div class="item panel panel-default"><!-- widgetBody -->
                                <div class="panel-heading">
                                    <h3 class="panel-title pull-left">Hijos</h3>
                                    <div class="pull-right">
                                        <button type="button" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                                        <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="panel-body">
                                    <?php
                                        // necessary for update action.
                                        if (! $modelHijos->isNewRecord) {
                                            echo Html::activeHiddenInput($modelHijos, "[{$i}]id");
                                        }
                                    ?>
                                    <div class="row">
                                        <div class="col-sm-6">

                                            <?= $form->field($modelHijos, "[{$i}]estudiante_id")
                                                    ->dropDownList(ArrayHelper::map(Estudiantes::find()
                                                                                    ->orderBy('ap_pat, ap_mat, nombres')
                                                                                    ->all(), 'id', 'fullnameinverted'),
                                                                    ['prompt' => Yii::t('backend', 'Select')]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                        <?php DynamicFormWidget::end(); ?>
                    </div>
                </div>
            </div>
        </p>
        <?php $this->endBlock(); ?>

        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
                        'label'   => Yii::t('backend', StringHelper::basename('backend\models\Padres')),
                        'content' => $this->blocks['main'],
                        'active'  => true,], [
                        'label'   => Yii::t('backend', StringHelper::basename('backend\models\Hijos')),
                        'content' => $this->blocks['hijos'],
                        'active'  => false,], 
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

