<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var backend\models\Estudiantes $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="estudiantes-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Estudiantes',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nombres')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_pat')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ap_mat')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'fec_nac')->textInput() ?>
			<?= $form->field($model, 'sex')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'ruta_foto')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'pais_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Paises::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'estado_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Estados::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= $form->field($model, 'tipo_sangre')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_fijo')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_movil')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tel_emergencia')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'contacto_emergencia')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\User::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'tipo_doc_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\TipoDocumentos::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= $form->field($model, 'num_doc_id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'direcc')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'fec_insc')->textInput() ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'religion_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Religiones::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= $form->field($model, 'rude')->textInput(['maxlength' => true]) ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'curso_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\Cursos::find()->all(), 'id', 'id'),
    ['prompt' => Yii::t('backend', 'Select')]
); ?>
			<?= $form->field($model, 'created_at')->textInput() ?>
			<?= $form->field($model, 'created_by')->textInput() ?>
			<?= $form->field($model, 'updated_at')->textInput() ?>
			<?= $form->field($model, 'updated_by')->textInput() ?>
			<?= $form->field($model, 'deleted')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => Yii::t('backend', StringHelper::basename('backend\models\Estudiantes')),
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

