<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "asistencia".
 *
 * @property string $id
 * @property integer $ciclo_id
 * @property integer $turno_id
 * @property integer $curso_id
 * @property integer $materia_id
 * @property integer $periodo_id
 * @property string $profesor_id
 * @property string $estudiante_id
 * @property integer $estado_id
 * @property integer $bimestre_id
 * @property string $fecha
 * @property string $comentario
 * @property string $licencia
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Bimestres $bimestre
 * @property \backend\models\Ciclos $ciclo
 * @property \backend\models\Turnos $turno
 * @property \backend\models\Cursos $curso
 * @property \backend\models\Materias $materia
 * @property \backend\models\Periodos $periodo
 * @property \backend\models\Profesores $profesor
 * @property \backend\models\Estudiantes $estudiante
 * @property \backend\models\EstadoAsistencia $estado
 * @property string $aliasModel
 */
abstract class Asistencia extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'asistencia';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ciclo_id', 'turno_id', 'curso_id', 'materia_id', 'periodo_id', 'profesor_id', 'estudiante_id', 'estado_id', 'bimestre_id', 'fecha'], 'required'],
            [['ciclo_id', 'turno_id', 'curso_id', 'materia_id', 'periodo_id', 'profesor_id', 'estudiante_id', 'estado_id', 'bimestre_id', 'deleted'], 'integer'],
            [['fecha'], 'safe'],
            [['comentario'], 'string', 'max' => 200],
            [['licencia'], 'string', 'max' => 300],
            [['bimestre_id'], 'exist', 'skipOnError' => true, 'targetClass' => Bimestres::className(), 'targetAttribute' => ['bimestre_id' => 'id']],
            [['ciclo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Ciclos::className(), 'targetAttribute' => ['ciclo_id' => 'id']],
            [['turno_id'], 'exist', 'skipOnError' => true, 'targetClass' => Turnos::className(), 'targetAttribute' => ['turno_id' => 'id']],
            [['curso_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cursos::className(), 'targetAttribute' => ['curso_id' => 'id']],
            [['materia_id'], 'exist', 'skipOnError' => true, 'targetClass' => Materias::className(), 'targetAttribute' => ['materia_id' => 'id']],
            [['periodo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Periodos::className(), 'targetAttribute' => ['periodo_id' => 'id']],
            [['profesor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Profesores::className(), 'targetAttribute' => ['profesor_id' => 'id']],
            [['estudiante_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estudiantes::className(), 'targetAttribute' => ['estudiante_id' => 'id']],
            [['estado_id'], 'exist', 'skipOnError' => true, 'targetClass' => EstadoAsistencia::className(), 'targetAttribute' => ['estado_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'ciclo_id' => Yii::t('backend', 'Ciclo ID'),
            'turno_id' => Yii::t('backend', 'Turno ID'),
            'curso_id' => Yii::t('backend', 'Curso ID'),
            'materia_id' => Yii::t('backend', 'Materia ID'),
            'periodo_id' => Yii::t('backend', 'Periodo ID'),
            'profesor_id' => Yii::t('backend', 'Profesor ID'),
            'estudiante_id' => Yii::t('backend', 'Estudiante ID'),
            'estado_id' => Yii::t('backend', 'Estado ID'),
            'bimestre_id' => Yii::t('backend', 'Bimestre ID'),
            'fecha' => Yii::t('backend', 'Fecha'),
            'comentario' => Yii::t('backend', 'Comentario'),
            'licencia' => Yii::t('backend', 'Licencia'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBimestre()
    {
        return $this->hasOne(\backend\models\Bimestres::className(), ['id' => 'bimestre_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclo()
    {
        return $this->hasOne(\backend\models\Ciclos::className(), ['id' => 'ciclo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTurno()
    {
        return $this->hasOne(\backend\models\Turnos::className(), ['id' => 'turno_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurso()
    {
        return $this->hasOne(\backend\models\Cursos::className(), ['id' => 'curso_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMateria()
    {
        return $this->hasOne(\backend\models\Materias::className(), ['id' => 'materia_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeriodo()
    {
        return $this->hasOne(\backend\models\Periodos::className(), ['id' => 'periodo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesor()
    {
        return $this->hasOne(\backend\models\Profesores::className(), ['id' => 'profesor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiante()
    {
        return $this->hasOne(\backend\models\Estudiantes::className(), ['id' => 'estudiante_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\backend\models\EstadoAsistencia::className(), ['id' => 'estado_id']);
    }




}
