<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "becas_detalle".
 *
 * @property string $id
 * @property string $beca_id
 * @property string $estudiante_id
 * @property integer $tipo_beca_id
 * @property integer $tipo_cuota_id
 * @property string $descuento
 * @property integer $numero_cuotas
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\TipoCuotas $tipoCuota
 * @property \backend\models\Becas $beca
 * @property \backend\models\Estudiantes $estudiante
 * @property \backend\models\TipoBecas $tipoBeca
 * @property string $aliasModel
 */
abstract class BecasDetalle extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'becas_detalle';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['beca_id', 'estudiante_id', 'tipo_beca_id', 'tipo_cuota_id', 'numero_cuotas'], 'required'],
            [['beca_id', 'estudiante_id', 'tipo_beca_id', 'tipo_cuota_id', 'numero_cuotas', 'deleted'], 'integer'],
            [['descuento'], 'number'],
            [['tipo_cuota_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoCuotas::className(), 'targetAttribute' => ['tipo_cuota_id' => 'id']],
            [['beca_id'], 'exist', 'skipOnError' => true, 'targetClass' => Becas::className(), 'targetAttribute' => ['beca_id' => 'id']],
            [['estudiante_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estudiantes::className(), 'targetAttribute' => ['estudiante_id' => 'id']],
            [['tipo_beca_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoBecas::className(), 'targetAttribute' => ['tipo_beca_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'beca_id' => Yii::t('backend', 'Beca ID'),
            'estudiante_id' => Yii::t('backend', 'Estudiante ID'),
            'tipo_beca_id' => Yii::t('backend', 'Tipo Beca ID'),
            'tipo_cuota_id' => Yii::t('backend', 'Tipo Cuota ID'),
            'descuento' => Yii::t('backend', 'Descuento'),
            'numero_cuotas' => Yii::t('backend', 'Numero Cuotas'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoCuota()
    {
        return $this->hasOne(\backend\models\TipoCuotas::className(), ['id' => 'tipo_cuota_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBeca()
    {
        return $this->hasOne(\backend\models\Becas::className(), ['id' => 'beca_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiante()
    {
        return $this->hasOne(\backend\models\Estudiantes::className(), ['id' => 'estudiante_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoBeca()
    {
        return $this->hasOne(\backend\models\TipoBecas::className(), ['id' => 'tipo_beca_id']);
    }




}
