<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "choferes".
 *
 * @property string $id
 * @property string $nombres
 * @property string $ap_pat
 * @property string $ap_mat
 * @property string $fec_nac
 * @property string $sex
 * @property string $ruta_foto
 * @property integer $pais_id
 * @property integer $estado_id
 * @property string $tipo_sangre
 * @property string $email
 * @property string $tel_fijo
 * @property string $tel_movil
 * @property string $tel_emergencia
 * @property string $contacto_emergencia
 * @property string $user_id
 * @property integer $tipo_doc_id
 * @property string $num_doc_id
 * @property string $direc
 * @property string $categoria_licencia
 * @property string $num_licencia
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Paises $pais
 * @property \backend\models\Estados $estado
 * @property \backend\models\User $user
 * @property \backend\models\TipoDocumentos $tipoDoc
 * @property \backend\models\Transporte[] $transportes
 * @property string $aliasModel
 */
abstract class Choferes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'choferes';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'sex', 'pais_id', 'tel_emergencia', 'contacto_emergencia', 'tipo_doc_id', 'num_doc_id', 'categoria_licencia', 'num_licencia'], 'required'],
            [['fec_nac'], 'safe'],
            [['pais_id', 'estado_id', 'user_id', 'tipo_doc_id', 'deleted'], 'integer'],
            [['nombres', 'ap_pat', 'ap_mat'], 'string', 'max' => 60],
            [['sex', 'categoria_licencia'], 'string', 'max' => 1],
            [['ruta_foto'], 'string', 'max' => 2000],
            [['tipo_sangre', 'tel_fijo', 'tel_movil', 'tel_emergencia'], 'string', 'max' => 20],
            [['email'], 'string', 'max' => 255],
            [['contacto_emergencia'], 'string', 'max' => 200],
            [['num_doc_id'], 'string', 'max' => 30],
            [['direc'], 'string', 'max' => 300],
            [['num_licencia'], 'string', 'max' => 15],
            [['pais_id'], 'exist', 'skipOnError' => true, 'targetClass' => Paises::className(), 'targetAttribute' => ['pais_id' => 'id']],
            [['estado_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estados::className(), 'targetAttribute' => ['estado_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['tipo_doc_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoDocumentos::className(), 'targetAttribute' => ['tipo_doc_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombres' => Yii::t('backend', 'Nombres'),
            'ap_pat' => Yii::t('backend', 'Ap Pat'),
            'ap_mat' => Yii::t('backend', 'Ap Mat'),
            'fec_nac' => Yii::t('backend', 'Fec Nac'),
            'sex' => Yii::t('backend', 'Sex'),
            'ruta_foto' => Yii::t('backend', 'Ruta Foto'),
            'pais_id' => Yii::t('backend', 'Pais ID'),
            'estado_id' => Yii::t('backend', 'Estado ID'),
            'tipo_sangre' => Yii::t('backend', 'Tipo Sangre'),
            'email' => Yii::t('backend', 'Email'),
            'tel_fijo' => Yii::t('backend', 'Tel Fijo'),
            'tel_movil' => Yii::t('backend', 'Tel Movil'),
            'tel_emergencia' => Yii::t('backend', 'Tel Emergencia'),
            'contacto_emergencia' => Yii::t('backend', 'Contacto Emergencia'),
            'user_id' => Yii::t('backend', 'User ID'),
            'tipo_doc_id' => Yii::t('backend', 'Tipo Doc ID'),
            'num_doc_id' => Yii::t('backend', 'Num Doc ID'),
            'direc' => Yii::t('backend', 'Direc'),
            'categoria_licencia' => Yii::t('backend', 'Categoria Licencia'),
            'num_licencia' => Yii::t('backend', 'Num Licencia'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPais()
    {
        return $this->hasOne(\backend\models\Paises::className(), ['id' => 'pais_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\backend\models\Estados::className(), ['id' => 'estado_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoDoc()
    {
        return $this->hasOne(\backend\models\TipoDocumentos::className(), ['id' => 'tipo_doc_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransportes()
    {
        return $this->hasMany(\backend\models\Transporte::className(), ['chofer_id' => 'id']);
    }




}
