<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "ciclos".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_abr
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Actividades[] $actividades
 * @property \backend\models\AdjuntosActividades[] $adjuntosActividades
 * @property \backend\models\Asistencia[] $asistencias
 * @property \backend\models\CiclosTurnos[] $ciclosTurnos
 * @property \backend\models\CiclosTurnosCursosParalelos[] $ciclosTurnosCursosParalelos
 * @property \backend\models\CiclosTurnosProfesores[] $ciclosTurnosProfesores
 * @property \backend\models\Cursos[] $cursos
 * @property \backend\models\EstudiantesActividades[] $estudiantesActividades
 * @property \backend\models\Facturas[] $facturas
 * @property \backend\models\FacturasDetalle[] $facturasDetalles
 * @property \backend\models\HorariosProfesores[] $horariosProfesores
 * @property \backend\models\PlanesDeClases[] $planesDeClases
 * @property \backend\models\Postulaciones[] $postulaciones
 * @property \backend\models\SistemaEvaluacion[] $sistemaEvaluacions
 * @property string $aliasModel
 */
abstract class Ciclos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ciclos';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'nombre_abr'], 'required'],
            [['deleted'], 'integer'],
            [['nombre'], 'string', 'max' => 20],
            [['nombre_abr'], 'string', 'max' => 3]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'nombre_abr' => Yii::t('backend', 'Nombre Abr'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividades()
    {
        return $this->hasMany(\backend\models\Actividades::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdjuntosActividades()
    {
        return $this->hasMany(\backend\models\AdjuntosActividades::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAsistencias()
    {
        return $this->hasMany(\backend\models\Asistencia::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclosTurnos()
    {
        return $this->hasMany(\backend\models\CiclosTurnos::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclosTurnosCursosParalelos()
    {
        return $this->hasMany(\backend\models\CiclosTurnosCursosParalelos::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclosTurnosProfesores()
    {
        return $this->hasMany(\backend\models\CiclosTurnosProfesores::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCursos()
    {
        return $this->hasMany(\backend\models\Cursos::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiantesActividades()
    {
        return $this->hasMany(\backend\models\EstudiantesActividades::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturas()
    {
        return $this->hasMany(\backend\models\Facturas::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturasDetalles()
    {
        return $this->hasMany(\backend\models\FacturasDetalle::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHorariosProfesores()
    {
        return $this->hasMany(\backend\models\HorariosProfesores::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanesDeClases()
    {
        return $this->hasMany(\backend\models\PlanesDeClases::className(), ['ciclo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostulaciones()
    {
        return $this->hasMany(\backend\models\Postulaciones::className(), ['ciclo_postulado' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSistemaEvaluacions()
    {
        return $this->hasMany(\backend\models\SistemaEvaluacion::className(), ['ciclo_id' => 'id']);
    }




}
