<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "datos_generales".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $direc
 * @property string $tel_fijo
 * @property string $email_contacto
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class DatosGenerales extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'datos_generales';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'direc'], 'required'],
            [['deleted'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['descripcion', 'email_contacto'], 'string', 'max' => 255],
            [['direc'], 'string', 'max' => 300],
            [['tel_fijo'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'descripcion' => Yii::t('backend', 'Descripcion'),
            'direc' => Yii::t('backend', 'Direc'),
            'tel_fijo' => Yii::t('backend', 'Tel Fijo'),
            'email_contacto' => Yii::t('backend', 'Email Contacto'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }




}
