<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "estudiantes".
 *
 * @property string $id
 * @property string $nombres
 * @property string $ap_pat
 * @property string $ap_mat
 * @property string $fec_nac
 * @property string $sex
 * @property string $ruta_foto
 * @property integer $pais_id
 * @property integer $estado_id
 * @property string $tipo_sangre
 * @property string $email
 * @property string $tel_fijo
 * @property string $tel_movil
 * @property string $tel_emergencia
 * @property string $contacto_emergencia
 * @property string $user_id
 * @property integer $tipo_doc_id
 * @property string $num_doc_id
 * @property string $direcc
 * @property string $fec_insc
 * @property integer $religion_id
 * @property string $rude
 * @property integer $curso_id
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\AdjuntosActividades[] $adjuntosActividades
 * @property \backend\models\AntecedentesMedicos[] $antecedentesMedicos
 * @property \backend\models\Asistencia[] $asistencias
 * @property \backend\models\Becas[] $becas
 * @property \backend\models\BecasDetalle[] $becasDetalles
 * @property \backend\models\Cuotas[] $cuotas
 * @property \backend\models\Cursos $curso
 * @property \backend\models\Paises $pais
 * @property \backend\models\Estados $estado
 * @property \backend\models\User $user
 * @property \backend\models\TipoDocumentos $tipoDoc
 * @property \backend\models\Religiones $religion
 * @property \backend\models\EstudiantesActividades[] $estudiantesActividades
 * @property \backend\models\Facturas[] $facturas
 * @property \backend\models\FacturasDetalle[] $facturasDetalles
 * @property \backend\models\Hijos[] $hijos
 * @property \backend\models\HistorialMedico[] $historialMedicos
 * @property \backend\models\IdiomasEstudiantes[] $idiomasEstudiantes
 * @property \backend\models\LibrosPrestamos[] $librosPrestamos
 * @property \backend\models\LlamadasAtencion[] $llamadasAtencions
 * @property \backend\models\TransporteDetalle[] $transporteDetalles
 * @property string $aliasModel
 */
abstract class Estudiantes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'estudiantes';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'sex', 'pais_id', 'tel_emergencia', 'contacto_emergencia', 'tipo_doc_id', 'num_doc_id', 'curso_id'], 'required'],
            [['fec_nac', 'fec_insc'], 'safe'],
            [['pais_id', 'estado_id', 'user_id', 'tipo_doc_id', 'religion_id', 'curso_id', 'deleted'], 'integer'],
            [['nombres', 'ap_pat', 'ap_mat'], 'string', 'max' => 60],
            [['sex'], 'string', 'max' => 1],
            [['ruta_foto'], 'string', 'max' => 2000],
            [['tipo_sangre', 'tel_fijo', 'tel_movil', 'tel_emergencia'], 'string', 'max' => 20],
            [['email'], 'string', 'max' => 255],
            [['contacto_emergencia'], 'string', 'max' => 200],
            [['num_doc_id'], 'string', 'max' => 30],
            [['direcc'], 'string', 'max' => 300],
            [['rude'], 'string', 'max' => 22],
            [['curso_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cursos::className(), 'targetAttribute' => ['curso_id' => 'id']],
            [['pais_id'], 'exist', 'skipOnError' => true, 'targetClass' => Paises::className(), 'targetAttribute' => ['pais_id' => 'id']],
            [['estado_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estados::className(), 'targetAttribute' => ['estado_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['tipo_doc_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoDocumentos::className(), 'targetAttribute' => ['tipo_doc_id' => 'id']],
            [['religion_id'], 'exist', 'skipOnError' => true, 'targetClass' => Religiones::className(), 'targetAttribute' => ['religion_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombres' => Yii::t('backend', 'Nombres'),
            'ap_pat' => Yii::t('backend', 'Ap Pat'),
            'ap_mat' => Yii::t('backend', 'Ap Mat'),
            'fec_nac' => Yii::t('backend', 'Fec Nac'),
            'sex' => Yii::t('backend', 'Sex'),
            'ruta_foto' => Yii::t('backend', 'Ruta Foto'),
            'pais_id' => Yii::t('backend', 'Pais ID'),
            'estado_id' => Yii::t('backend', 'Estado ID'),
            'tipo_sangre' => Yii::t('backend', 'Tipo Sangre'),
            'email' => Yii::t('backend', 'Email'),
            'tel_fijo' => Yii::t('backend', 'Tel Fijo'),
            'tel_movil' => Yii::t('backend', 'Tel Movil'),
            'tel_emergencia' => Yii::t('backend', 'Tel Emergencia'),
            'contacto_emergencia' => Yii::t('backend', 'Contacto Emergencia'),
            'user_id' => Yii::t('backend', 'User ID'),
            'tipo_doc_id' => Yii::t('backend', 'Tipo Doc ID'),
            'num_doc_id' => Yii::t('backend', 'Num Doc ID'),
            'direcc' => Yii::t('backend', 'Direcc'),
            'fec_insc' => Yii::t('backend', 'Fec Insc'),
            'religion_id' => Yii::t('backend', 'Religion ID'),
            'rude' => Yii::t('backend', 'Rude'),
            'curso_id' => Yii::t('backend', 'Curso ID'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdjuntosActividades()
    {
        return $this->hasMany(\backend\models\AdjuntosActividades::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAntecedentesMedicos()
    {
        return $this->hasMany(\backend\models\AntecedentesMedicos::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAsistencias()
    {
        return $this->hasMany(\backend\models\Asistencia::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBecas()
    {
        return $this->hasMany(\backend\models\Becas::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBecasDetalles()
    {
        return $this->hasMany(\backend\models\BecasDetalle::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuotas()
    {
        return $this->hasMany(\backend\models\Cuotas::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurso()
    {
        return $this->hasOne(\backend\models\Cursos::className(), ['id' => 'curso_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPais()
    {
        return $this->hasOne(\backend\models\Paises::className(), ['id' => 'pais_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\backend\models\Estados::className(), ['id' => 'estado_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoDoc()
    {
        return $this->hasOne(\backend\models\TipoDocumentos::className(), ['id' => 'tipo_doc_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReligion()
    {
        return $this->hasOne(\backend\models\Religiones::className(), ['id' => 'religion_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiantesActividades()
    {
        return $this->hasMany(\backend\models\EstudiantesActividades::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturas()
    {
        return $this->hasMany(\backend\models\Facturas::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacturasDetalles()
    {
        return $this->hasMany(\backend\models\FacturasDetalle::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHijos()
    {
        return $this->hasMany(\backend\models\Hijos::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHistorialMedicos()
    {
        return $this->hasMany(\backend\models\HistorialMedico::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdiomasEstudiantes()
    {
        return $this->hasMany(\backend\models\IdiomasEstudiantes::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLibrosPrestamos()
    {
        return $this->hasMany(\backend\models\LibrosPrestamos::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLlamadasAtencions()
    {
        return $this->hasMany(\backend\models\LlamadasAtencion::className(), ['estudiante_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransporteDetalles()
    {
        return $this->hasMany(\backend\models\TransporteDetalle::className(), ['estudiante_id' => 'id']);
    }




}
