<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "facturas_detalle".
 *
 * @property string $id
 * @property string $factura_id
 * @property string $estudiante_id
 * @property integer $ciclo_id
 * @property integer $turno_id
 * @property integer $curso_id
 * @property integer $paralelo_id
 * @property string $cuota_id
 * @property integer $cantidad
 * @property double $monto
 * @property double $descuento
 * @property double $total
 * @property integer $payed
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Cuotas $cuota
 * @property \backend\models\Facturas $factura
 * @property \backend\models\Estudiantes $estudiante
 * @property \backend\models\Ciclos $ciclo
 * @property \backend\models\Turnos $turno
 * @property \backend\models\Cursos $curso
 * @property \backend\models\Paralelos $paralelo
 * @property string $aliasModel
 */
abstract class FacturasDetalle extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'facturas_detalle';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['factura_id', 'estudiante_id', 'ciclo_id', 'turno_id', 'curso_id', 'paralelo_id', 'cuota_id', 'cantidad', 'monto', 'total'], 'required'],
            [['factura_id', 'estudiante_id', 'ciclo_id', 'turno_id', 'curso_id', 'paralelo_id', 'cuota_id', 'cantidad', 'payed', 'deleted'], 'integer'],
            [['monto', 'descuento', 'total'], 'number'],
            [['cuota_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cuotas::className(), 'targetAttribute' => ['cuota_id' => 'id']],
            [['factura_id'], 'exist', 'skipOnError' => true, 'targetClass' => Facturas::className(), 'targetAttribute' => ['factura_id' => 'id']],
            [['estudiante_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estudiantes::className(), 'targetAttribute' => ['estudiante_id' => 'id']],
            [['ciclo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Ciclos::className(), 'targetAttribute' => ['ciclo_id' => 'id']],
            [['turno_id'], 'exist', 'skipOnError' => true, 'targetClass' => Turnos::className(), 'targetAttribute' => ['turno_id' => 'id']],
            [['curso_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cursos::className(), 'targetAttribute' => ['curso_id' => 'id']],
            [['paralelo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Paralelos::className(), 'targetAttribute' => ['paralelo_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'factura_id' => Yii::t('backend', 'Factura ID'),
            'estudiante_id' => Yii::t('backend', 'Estudiante ID'),
            'ciclo_id' => Yii::t('backend', 'Ciclo ID'),
            'turno_id' => Yii::t('backend', 'Turno ID'),
            'curso_id' => Yii::t('backend', 'Curso ID'),
            'paralelo_id' => Yii::t('backend', 'Paralelo ID'),
            'cuota_id' => Yii::t('backend', 'Cuota ID'),
            'cantidad' => Yii::t('backend', 'Cantidad'),
            'monto' => Yii::t('backend', 'Monto'),
            'descuento' => Yii::t('backend', 'Descuento'),
            'total' => Yii::t('backend', 'Total'),
            'payed' => Yii::t('backend', 'Payed'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuota()
    {
        return $this->hasOne(\backend\models\Cuotas::className(), ['id' => 'cuota_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFactura()
    {
        return $this->hasOne(\backend\models\Facturas::className(), ['id' => 'factura_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiante()
    {
        return $this->hasOne(\backend\models\Estudiantes::className(), ['id' => 'estudiante_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclo()
    {
        return $this->hasOne(\backend\models\Ciclos::className(), ['id' => 'ciclo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTurno()
    {
        return $this->hasOne(\backend\models\Turnos::className(), ['id' => 'turno_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurso()
    {
        return $this->hasOne(\backend\models\Cursos::className(), ['id' => 'curso_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParalelo()
    {
        return $this->hasOne(\backend\models\Paralelos::className(), ['id' => 'paralelo_id']);
    }




}
