<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "historial_medico".
 *
 * @property string $id
 * @property string $estudiante_id
 * @property string $profesor_id
 * @property string $administrativo_id
 * @property integer $grados_temp
 * @property integer $presion_sistolica
 * @property integer $presion_diastolica
 * @property string $sintomas
 * @property string $antecedente_sintomas
 * @property string $diagnostico
 * @property string $medicacion_aplicada
 * @property string $medicacion_sugerida
 * @property string $recomendaciones
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Administrativos $administrativo
 * @property \backend\models\Estudiantes $estudiante
 * @property \backend\models\Profesores $profesor
 * @property string $aliasModel
 */
abstract class HistorialMedico extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'historial_medico';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['estudiante_id', 'profesor_id', 'administrativo_id', 'grados_temp', 'presion_sistolica', 'presion_diastolica', 'deleted'], 'integer'],
            [['sintomas', 'diagnostico'], 'required'],
            [['sintomas', 'antecedente_sintomas', 'diagnostico', 'medicacion_aplicada', 'medicacion_sugerida', 'recomendaciones'], 'string', 'max' => 255],
            [['administrativo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Administrativos::className(), 'targetAttribute' => ['administrativo_id' => 'id']],
            [['estudiante_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estudiantes::className(), 'targetAttribute' => ['estudiante_id' => 'id']],
            [['profesor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Profesores::className(), 'targetAttribute' => ['profesor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'estudiante_id' => Yii::t('backend', 'Estudiante ID'),
            'profesor_id' => Yii::t('backend', 'Profesor ID'),
            'administrativo_id' => Yii::t('backend', 'Administrativo ID'),
            'grados_temp' => Yii::t('backend', 'Grados Temp'),
            'presion_sistolica' => Yii::t('backend', 'Presion Sistolica'),
            'presion_diastolica' => Yii::t('backend', 'Presion Diastolica'),
            'sintomas' => Yii::t('backend', 'Sintomas'),
            'antecedente_sintomas' => Yii::t('backend', 'Antecedente Sintomas'),
            'diagnostico' => Yii::t('backend', 'Diagnostico'),
            'medicacion_aplicada' => Yii::t('backend', 'Medicacion Aplicada'),
            'medicacion_sugerida' => Yii::t('backend', 'Medicacion Sugerida'),
            'recomendaciones' => Yii::t('backend', 'Recomendaciones'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdministrativo()
    {
        return $this->hasOne(\backend\models\Administrativos::className(), ['id' => 'administrativo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiante()
    {
        return $this->hasOne(\backend\models\Estudiantes::className(), ['id' => 'estudiante_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesor()
    {
        return $this->hasOne(\backend\models\Profesores::className(), ['id' => 'profesor_id']);
    }




}
