<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "llamadas_atencion".
 *
 * @property string $id
 * @property integer $tipo_llamada_id
 * @property string $estudiante_id
 * @property string $profesor_id
 * @property string $administrativo_id
 * @property string $fecha
 * @property string $explicacion
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Administrativos $administrativo
 * @property \backend\models\TipoLlamadaAtencion $tipoLlamada
 * @property \backend\models\Estudiantes $estudiante
 * @property \backend\models\Profesores $profesor
 * @property \backend\models\MedidasDisciplinariasTomadas[] $medidasDisciplinariasTomadas
 * @property \backend\models\SeguimientoLlamadasAtencion[] $seguimientoLlamadasAtencions
 * @property string $aliasModel
 */
abstract class LlamadasAtencion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'llamadas_atencion';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tipo_llamada_id', 'estudiante_id', 'fecha', 'explicacion'], 'required'],
            [['tipo_llamada_id', 'estudiante_id', 'profesor_id', 'administrativo_id', 'deleted'], 'integer'],
            [['fecha'], 'safe'],
            [['explicacion'], 'string', 'max' => 400],
            [['administrativo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Administrativos::className(), 'targetAttribute' => ['administrativo_id' => 'id']],
            [['tipo_llamada_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoLlamadaAtencion::className(), 'targetAttribute' => ['tipo_llamada_id' => 'id']],
            [['estudiante_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estudiantes::className(), 'targetAttribute' => ['estudiante_id' => 'id']],
            [['profesor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Profesores::className(), 'targetAttribute' => ['profesor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'tipo_llamada_id' => Yii::t('backend', 'Tipo Llamada ID'),
            'estudiante_id' => Yii::t('backend', 'Estudiante ID'),
            'profesor_id' => Yii::t('backend', 'Profesor ID'),
            'administrativo_id' => Yii::t('backend', 'Administrativo ID'),
            'fecha' => Yii::t('backend', 'Fecha'),
            'explicacion' => Yii::t('backend', 'Explicacion'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdministrativo()
    {
        return $this->hasOne(\backend\models\Administrativos::className(), ['id' => 'administrativo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoLlamada()
    {
        return $this->hasOne(\backend\models\TipoLlamadaAtencion::className(), ['id' => 'tipo_llamada_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiante()
    {
        return $this->hasOne(\backend\models\Estudiantes::className(), ['id' => 'estudiante_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesor()
    {
        return $this->hasOne(\backend\models\Profesores::className(), ['id' => 'profesor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMedidasDisciplinariasTomadas()
    {
        return $this->hasMany(\backend\models\MedidasDisciplinariasTomadas::className(), ['llamada_atencion_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSeguimientoLlamadasAtencions()
    {
        return $this->hasMany(\backend\models\SeguimientoLlamadasAtencion::className(), ['llamada_atencion_id' => 'id']);
    }




}
