<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "log".
 *
 * @property string $id
 * @property string $fecha
 * @property string $user_id
 * @property string $secuencia
 * @property string $accion
 * @property string $basedatos
 * @property string $consulta
 *
 * @property \backend\models\User $user
 * @property string $aliasModel
 */
abstract class Log extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'log';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha', 'user_id', 'secuencia', 'accion', 'basedatos', 'consulta'], 'required'],
            [['fecha'], 'safe'],
            [['user_id', 'secuencia'], 'integer'],
            [['accion', 'basedatos'], 'string', 'max' => 50],
            [['consulta'], 'string', 'max' => 3000],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'fecha' => Yii::t('backend', 'Fecha'),
            'user_id' => Yii::t('backend', 'User ID'),
            'secuencia' => Yii::t('backend', 'Secuencia'),
            'accion' => Yii::t('backend', 'Accion'),
            'basedatos' => Yii::t('backend', 'Basedatos'),
            'consulta' => Yii::t('backend', 'Consulta'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'user_id']);
    }




}
