<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "materias".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_corto
 * @property integer $grupo_id
 * @property integer $orden
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Actividades[] $actividades
 * @property \backend\models\AdjuntosActividades[] $adjuntosActividades
 * @property \backend\models\Asistencia[] $asistencias
 * @property \backend\models\EstudiantesActividades[] $estudiantesActividades
 * @property \backend\models\HorariosProfesores[] $horariosProfesores
 * @property \backend\models\GruposMaterias $grupo
 * @property \backend\models\PlanesDeClases[] $planesDeClases
 * @property \backend\models\SistemaEvaluacion[] $sistemaEvaluacions
 * @property string $aliasModel
 */
abstract class Materias extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'materias';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'nombre_corto', 'grupo_id'], 'required'],
            [['grupo_id', 'orden', 'deleted'], 'integer'],
            [['nombre', 'nombre_corto'], 'string', 'max' => 50],
            [['grupo_id'], 'exist', 'skipOnError' => true, 'targetClass' => GruposMaterias::className(), 'targetAttribute' => ['grupo_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'nombre_corto' => Yii::t('backend', 'Nombre Corto'),
            'grupo_id' => Yii::t('backend', 'Grupo ID'),
            'orden' => Yii::t('backend', 'Orden'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActividades()
    {
        return $this->hasMany(\backend\models\Actividades::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdjuntosActividades()
    {
        return $this->hasMany(\backend\models\AdjuntosActividades::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAsistencias()
    {
        return $this->hasMany(\backend\models\Asistencia::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiantesActividades()
    {
        return $this->hasMany(\backend\models\EstudiantesActividades::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHorariosProfesores()
    {
        return $this->hasMany(\backend\models\HorariosProfesores::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupo()
    {
        return $this->hasOne(\backend\models\GruposMaterias::className(), ['id' => 'grupo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlanesDeClases()
    {
        return $this->hasMany(\backend\models\PlanesDeClases::className(), ['materia_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSistemaEvaluacions()
    {
        return $this->hasMany(\backend\models\SistemaEvaluacion::className(), ['materia_id' => 'id']);
    }




}
