<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "medidas_disciplinarias_tomadas".
 *
 * @property string $id
 * @property string $llamada_atencion_id
 * @property integer $tipo_medida_id
 * @property string $fecha
 * @property string $explicacion
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\TipoMedidasDisciplinarias $tipoMedida
 * @property \backend\models\LlamadasAtencion $llamadaAtencion
 * @property string $aliasModel
 */
abstract class MedidasDisciplinariasTomadas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'medidas_disciplinarias_tomadas';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['llamada_atencion_id', 'tipo_medida_id', 'fecha', 'explicacion'], 'required'],
            [['llamada_atencion_id', 'tipo_medida_id', 'deleted'], 'integer'],
            [['fecha'], 'safe'],
            [['explicacion'], 'string', 'max' => 400],
            [['tipo_medida_id'], 'exist', 'skipOnError' => true, 'targetClass' => TipoMedidasDisciplinarias::className(), 'targetAttribute' => ['tipo_medida_id' => 'id']],
            [['llamada_atencion_id'], 'exist', 'skipOnError' => true, 'targetClass' => LlamadasAtencion::className(), 'targetAttribute' => ['llamada_atencion_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'llamada_atencion_id' => Yii::t('backend', 'Llamada Atencion ID'),
            'tipo_medida_id' => Yii::t('backend', 'Tipo Medida ID'),
            'fecha' => Yii::t('backend', 'Fecha'),
            'explicacion' => Yii::t('backend', 'Explicacion'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoMedida()
    {
        return $this->hasOne(\backend\models\TipoMedidasDisciplinarias::className(), ['id' => 'tipo_medida_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLlamadaAtencion()
    {
        return $this->hasOne(\backend\models\LlamadasAtencion::className(), ['id' => 'llamada_atencion_id']);
    }




}
