<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "periodos".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $hora_ini
 * @property string $hora_fin
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Asistencia[] $asistencias
 * @property \backend\models\HorariosProfesores[] $horariosProfesores
 * @property string $aliasModel
 */
abstract class Periodos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'periodos';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hora_ini', 'hora_fin'], 'required'],
            [['hora_ini', 'hora_fin'], 'safe'],
            [['deleted'], 'integer'],
            [['nombre'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'hora_ini' => Yii::t('backend', 'Hora Ini'),
            'hora_fin' => Yii::t('backend', 'Hora Fin'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAsistencias()
    {
        return $this->hasMany(\backend\models\Asistencia::className(), ['periodo_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHorariosProfesores()
    {
        return $this->hasMany(\backend\models\HorariosProfesores::className(), ['periodo_id' => 'id']);
    }




}
