<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "planes_de_clases".
 *
 * @property string $id
 * @property string $profesor_id
 * @property integer $ciclo_id
 * @property integer $turno_id
 * @property integer $curso_id
 * @property integer $paralelo_id
 * @property integer $materia_id
 * @property integer $hora
 * @property integer $dia
 * @property string $objetivo
 * @property string $procedimiento
 * @property string $pag_libro
 * @property string $otros_recursos
 * @property string $tareas
 * @property string $fecha
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Materias $materia
 * @property \backend\models\Profesores $profesor
 * @property \backend\models\Ciclos $ciclo
 * @property \backend\models\Turnos $turno
 * @property \backend\models\Cursos $curso
 * @property \backend\models\Paralelos $paralelo
 * @property string $aliasModel
 */
abstract class PlanesDeClases extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'planes_de_clases';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['profesor_id', 'ciclo_id', 'turno_id', 'curso_id', 'paralelo_id', 'materia_id', 'hora', 'dia', 'fecha'], 'required'],
            [['profesor_id', 'ciclo_id', 'turno_id', 'curso_id', 'paralelo_id', 'materia_id', 'hora', 'dia', 'deleted'], 'integer'],
            [['fecha'], 'safe'],
            [['objetivo', 'procedimiento', 'otros_recursos', 'tareas'], 'string', 'max' => 255],
            [['pag_libro'], 'string', 'max' => 100],
            [['materia_id'], 'exist', 'skipOnError' => true, 'targetClass' => Materias::className(), 'targetAttribute' => ['materia_id' => 'id']],
            [['profesor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Profesores::className(), 'targetAttribute' => ['profesor_id' => 'id']],
            [['ciclo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Ciclos::className(), 'targetAttribute' => ['ciclo_id' => 'id']],
            [['turno_id'], 'exist', 'skipOnError' => true, 'targetClass' => Turnos::className(), 'targetAttribute' => ['turno_id' => 'id']],
            [['curso_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cursos::className(), 'targetAttribute' => ['curso_id' => 'id']],
            [['paralelo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Paralelos::className(), 'targetAttribute' => ['paralelo_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'profesor_id' => Yii::t('backend', 'Profesor ID'),
            'ciclo_id' => Yii::t('backend', 'Ciclo ID'),
            'turno_id' => Yii::t('backend', 'Turno ID'),
            'curso_id' => Yii::t('backend', 'Curso ID'),
            'paralelo_id' => Yii::t('backend', 'Paralelo ID'),
            'materia_id' => Yii::t('backend', 'Materia ID'),
            'hora' => Yii::t('backend', 'Hora'),
            'dia' => Yii::t('backend', 'Dia'),
            'objetivo' => Yii::t('backend', 'Objetivo'),
            'procedimiento' => Yii::t('backend', 'Procedimiento'),
            'pag_libro' => Yii::t('backend', 'Pag Libro'),
            'otros_recursos' => Yii::t('backend', 'Otros Recursos'),
            'tareas' => Yii::t('backend', 'Tareas'),
            'fecha' => Yii::t('backend', 'Fecha'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMateria()
    {
        return $this->hasOne(\backend\models\Materias::className(), ['id' => 'materia_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesor()
    {
        return $this->hasOne(\backend\models\Profesores::className(), ['id' => 'profesor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCiclo()
    {
        return $this->hasOne(\backend\models\Ciclos::className(), ['id' => 'ciclo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTurno()
    {
        return $this->hasOne(\backend\models\Turnos::className(), ['id' => 'turno_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurso()
    {
        return $this->hasOne(\backend\models\Cursos::className(), ['id' => 'curso_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParalelo()
    {
        return $this->hasOne(\backend\models\Paralelos::className(), ['id' => 'paralelo_id']);
    }




}
