<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "rutas".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $zonas
 * @property integer $deleted
 *
 * @property \backend\models\Transporte[] $transportes
 * @property string $aliasModel
 */
abstract class Rutas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rutas';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'zonas', 'deleted'], 'required'],
            [['deleted'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['zonas'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'zonas' => Yii::t('backend', 'Zonas'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransportes()
    {
        return $this->hasMany(\backend\models\Transporte::className(), ['ruta_id' => 'id']);
    }




}
