<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tipo_documentos".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Administrativos[] $administrativos
 * @property \backend\models\Choferes[] $choferes
 * @property \backend\models\Estudiantes[] $estudiantes
 * @property \backend\models\Padres[] $padres
 * @property \backend\models\Profesores[] $profesores
 * @property string $aliasModel
 */
abstract class TipoDocumentos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tipo_documentos';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['deleted'], 'integer'],
            [['nombre'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'nombre' => Yii::t('backend', 'Nombre'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdministrativos()
    {
        return $this->hasMany(\backend\models\Administrativos::className(), ['tipo_doc_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChoferes()
    {
        return $this->hasMany(\backend\models\Choferes::className(), ['tipo_doc_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstudiantes()
    {
        return $this->hasMany(\backend\models\Estudiantes::className(), ['tipo_doc_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPadres()
    {
        return $this->hasMany(\backend\models\Padres::className(), ['tipo_doc_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesores()
    {
        return $this->hasMany(\backend\models\Profesores::className(), ['tipo_doc_id' => 'id']);
    }




}
