<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "transporte".
 *
 * @property integer $id
 * @property integer $ruta_id
 * @property integer $vehiculo_id
 * @property string $chofer_id
 * @property integer $deleted
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \backend\models\Choferes $chofer
 * @property \backend\models\Rutas $ruta
 * @property \backend\models\Vehiculos $vehiculo
 * @property \backend\models\TransporteDetalle[] $transporteDetalles
 * @property string $aliasModel
 */
abstract class Transporte extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transporte';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ruta_id', 'vehiculo_id', 'chofer_id'], 'required'],
            [['ruta_id', 'vehiculo_id', 'chofer_id', 'deleted'], 'integer'],
            [['chofer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Choferes::className(), 'targetAttribute' => ['chofer_id' => 'id']],
            [['ruta_id'], 'exist', 'skipOnError' => true, 'targetClass' => Rutas::className(), 'targetAttribute' => ['ruta_id' => 'id']],
            [['vehiculo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vehiculos::className(), 'targetAttribute' => ['vehiculo_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'ruta_id' => Yii::t('backend', 'Ruta ID'),
            'vehiculo_id' => Yii::t('backend', 'Vehiculo ID'),
            'chofer_id' => Yii::t('backend', 'Chofer ID'),
            'created_at' => Yii::t('backend', 'Created At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'updated_by' => Yii::t('backend', 'Updated By'),
            'deleted' => Yii::t('backend', 'Deleted'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChofer()
    {
        return $this->hasOne(\backend\models\Choferes::className(), ['id' => 'chofer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuta()
    {
        return $this->hasOne(\backend\models\Rutas::className(), ['id' => 'ruta_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehiculo()
    {
        return $this->hasOne(\backend\models\Vehiculos::className(), ['id' => 'vehiculo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransporteDetalles()
    {
        return $this->hasMany(\backend\models\TransporteDetalle::className(), ['transporte_id' => 'id']);
    }




}
